export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_EDIT = 'COMMENT_EDIT';
export const COMMENT_REMOVE = 'COMMENT_REMOVE';
export const COMMENT_THUMB_UP = 'COMMENT_THUMB_UP';
export const COMMENT_THUMB_DOWN = 'COMMENT_THUMB_DOWN';